name: Discord notification

on: push

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: 'New changes: {{ EVENT_PAYLOAD.commits[0].message }}'
